compile:
	g++ -pthread main.cpp Client_Account.cpp Savings_Account.cpp Term_Account.cpp Bank.cpp -o Bank_System
	./Bank_System 

test2:
	g++ -pthread main.cpp Client_Account.cpp Savings_Account.cpp Term_Account.cpp Bank.cpp -o Bank_System
	./Bank_System 
	Pahlavonjon
likes:
	g++ likes.cpp -o likes
	./likes
