compile:
	g++ polymorphism.cpp -o polymorphism
	./polymorphism


# # TEST MAKEFILE  
# no need to write the user input! just upload a file

# mycode: main.cpp sum.o 
#         g++ -o mycode main.cpp sum.o 

# sum.o: sum.cpp 
#         g++ -c sum.cpp

# test:
#         ./mycode < code1.txt